services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception_network

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/anaiscaire/data/mariadb

networks:
  inception_network:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt